packages:
  - apps/nextjs
  - packages/*
  - tooling/*
catalog:
  '@biomejs/biome': ^1.9.4
  prettier: ^3.7.4
  tailwindcss: ^3.4.15
  typescript: ^5.9.3
  zod: ^3.25.49
  '@tanstack/react-query': ^5.90.12
  '@trpc/client': ^11.8.0
  '@trpc/tanstack-react-query': ^11.8.0
  '@trpc/server': ^11.8.0
  vitest: ^3.2.4
  '@vitest/coverage-v8': ^3.2.4
catalogs:
  react19:
    react: 19.2.3
    react-dom: 19.2.3
    '@types/react': ^19.2.7
    '@types/react-dom': ^19.2.3
onlyBuiltDependencies:
  - '@biomejs/biome'
  - '@vercel/speed-insights'
  - bufferutil
  - core-js-pure
  - duckdb
  - esbuild
  - sharp
  - supabase
  - utf-8-validate
